### ISSUE TITLE
error on compile 

### ISSUE THREAD

**Issue by rayzer86** [magnusrofhok/mixer#1]
[error.log](https://github.com/magnusrofhok/mixer/files/8680487/error.log)

**Comment by magnusrofhok** [comment]
Hittade denna
It seems like the default wx configuration on your system is base and not
wxGTK (you can confirm this by doing "wx-config --list"). So you have to
either explicitly select wxGTK (wx-config --toolkit=gtk) or, better,
reinstall wxGTK which should make it the default choice.
